### ISSUE TITLE
Office 365 Mailkit Secure Socket Issue

### ISSUE THREAD

**Issue by sssdev-1** [cofoundry-cms/Cofoundry.Plugins.Mail.MailKit#1]
When creating a connection with mailkit, Office 365 needs the secure socket option StartTLS. 
![image](https://user-images.githubusercontent.com/55808911/65711690-6e64e180-e063-11e9-8f64-0afe6ace0ecc.png)

I specify the socketoption StartTls which initiates a SSL session before any SMTP traffic is sent. Which then allows me to send mail over to smtp.office365.com:587. But with the mailkit plugin, I can only specify enableSsl, when looking at the cofoundry documentation for plugins.mail.mailkit. So I am getting "The handshake failed due to an unexpected packet format" in my error log. Which makes sense, because on starting the connection, I cannot calling start tls to begin the ssl session. Is there a way in the mailkit plugin to specify that, or override the connect to do that?

**Comment by HeyJoel** [comment]
It's been a while since I've looked at MailKit, but I did a little digging and it seems that specifying useSsl `false` might actually work for you, as for port 587 it would enable TLS automatically if supported, see [this issue](https://github.com/jstedfast/MailKit/issues/565#issuecomment-332535806):

> There are 2 types of "SSL":
>
> 1. SSL/TLS immediately on connect (i.e. no plain-text commands/responses/greetings are ever sent between client/server)
> 2. SSL/TLS via the STARTTLS command.
>
> Port 25 and 587 use mode 2. Port 465 uses mode 1.
> 
> The Connect() method that takes a useSsl refers to type 1 (i.e. true means use mode 1 while false means use mode 2 if-and-only-if-it-is-available).

The parameter is also referenced in the remarks seciton in [the docs](http://www.mimekit.net/docs/html/M_MailKit_MailService_ConnectAsync_3.htm).

> The useSsl argument only controls whether or not the client makes an SSL-wrapped connection. In other words, even if the useSsl parameter is false, SSL/TLS may still be used if the mail server supports the STARTTLS extension.

That behaviour was a bit of a surprise to me and I think it's a bit confusing, so I wonder if we can better expose this configuration in Cofoundry or simplify things a little?

If you'd rather force `SecureSocketOptions.StartTls` then for now the only way to do that is to create your own `ISmtpClientConnectionConfiguration` implementation using the exisiting `SmtpClientConnectionConfiguration` as a base e.g:

```csharp
using System;
using System.Threading.Tasks;
using Cofoundry.Plugins.Mail.MailKit;
using MailKit.Net.Smtp;
using MailKit.Security;

public class CustomSmtpClientConnectionConfiguration : SmtpClientConnectionConfiguration
{
    private readonly MailKitSettings _mailKitSettings;

    public CustomSmtpClientConnectionConfiguration(
        MailKitSettings mailKitSettings
        )
        : base(mailKitSettings)
    {
        _mailKitSettings = mailKitSettings;
    }

    public override void Connect(SmtpClient smtpClient)
    {
        if (smtpClient == null) throw new ArgumentNullException(nameof(smtpClient));

        if (smtpClient.IsConnected) return;

        smtpClient.Connect(_mailKitSettings.Host, _mailKitSettings.Port, SecureSocketOptions.StartTls);

        if (!string.IsNullOrWhiteSpace(_mailKitSettings.UserName) && !smtpClient.IsAuthenticated)
        {
            smtpClient.Authenticate(_mailKitSettings.UserName, _mailKitSettings.Password);
        }
    }

    public override async Task ConnectAsync(SmtpClient smtpClient)
    {
        if (smtpClient == null) throw new ArgumentNullException(nameof(smtpClient));

        if (smtpClient.IsConnected) return;

        await smtpClient.ConnectAsync(_mailKitSettings.Host, _mailKitSettings.Port, SecureSocketOptions.StartTls);

        if (!string.IsNullOrWhiteSpace(_mailKitSettings.UserName))
        {
            await smtpClient.AuthenticateAsync(_mailKitSettings.UserName, _mailKitSettings.Password);
        }
    }
}
```

You then need to override the existing implementation with our DI system:

```csharp
using Cofoundry.Core.DependencyInjection;

public class DependencyRegistration : IDependencyRegistration
{
    public void Register(IContainerRegister container)
    {
        container.Register<ISmtpClientConnectionConfiguration, SmtpClientConnectionConfiguration>(RegistrationOptions.Override());
    }
}
```

**Comment by sssdev-1** [comment]
Hey Joel,

Setting enableSSl to false worked with port 587 specified. It is a bit different than how I've done it in the past with mailkit, but thank you for the clarification. No need to do the override, but glad I know how to if needed. Thank you for the help.
